# Config file for automatic testing at travis-ci.org
language: python
sudo: false

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# command to install dependencies
install: pip install -r requirements.txt

before_script:
    - flake8 planetaryimage
    - get_mission_data

# command to run tests
script: py.test --doctest-modules --ignore=setup.py
